### ISSUE TITLE
Error: Cannot find module '../doc/directives.js' after upgrade to 17.1.x

### ISSUE THREAD

**Issue by yeongsheng-tan** [badeball/cypress-cucumber-preprocessor#1023]
### Current behavior

Upgrade `@badeballcypress-cucumber-preprocessor` from v16.x to v17.1.x and on starting cypress e2e testing, this error stack from cypress starts:
```[cy:run  ] It threw an error when required, check the stack trace below:
[cy:run  ]
[cy:run  ] Error: Cannot find module '../doc/directives.js'
[cy:run  ] Require stack:
[cy:run  ] - $PROJECT_ROOT/node_modules/yaml/dist/compose/composer.js
[cy:run  ] - $PROJECT_ROOT/node_modules/yaml/dist/index.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/configuration/from_file.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/configuration/index.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/cli/index.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/@cucumber/cucumber/lib/index.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/dist/add-cucumber-preprocessor-plugin.js
[cy:run  ] - $PROJECT_ROOT/node_modules/@badeball/cypress-cucumber-preprocessor/dist/entrypoint-node.js
[cy:run  ] - $PROJECT_ROOT/cypress/config/ci.ts
[cy:run  ] -$HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js
[cy:run  ] - $HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/require_async_child.js
[cy:run  ]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
[cy:run  ]     at Function.Module._resolveFilename ($HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/node_modules/tsconfig-paths/lib/register.js:75:40)
[cy:run  ]     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] ($HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
[cy:run  ]     at Function.Module._load (node:internal/modules/cjs/loader:928:27)
[cy:run  ]     at Module.require (node:internal/modules/cjs/loader:1149:19)
[cy:run  ]     at require (node:internal/modules/helpers:121:18)
[cy:run  ]     at Object.<anonymous> ($PROJECT_ROOT/node_modules/yaml/dist/compose/composer.js:3:18)
[cy:run  ]     at Module._compile (node:internal/modules/cjs/loader:1267:14)
[cy:run  ]     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
[cy:run  ]     at Object.require.extensions.<computed> [as .js] ($HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:851:20)
[cy:run  ]     at Module.load (node:internal/modules/cjs/loader:1125:32)
[cy:run  ]     at Function.Module._load (node:internal/modules/cjs/loader:965:12)
[cy:run  ]     at Module.require (node:internal/modules/cjs/loader:1149:19)
[cy:run  ]     at require (node:internal/modules/helpers:121:18)
[cy:run  ]     at Object.<anonymous> ($PROJECT_ROOT/node_modules/yaml/dist/index.js:3:16)
[cy:run  ]     at Module._compile (node:internal/modules/cjs/loader:1267:14)
[cy:run  ]     at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
[cy:run  ]     at Object.require.extensions.<computed> [as .js] ($HOME/Library/Caches/Cypress/12.13.0/Cypress.app/Contents/Resources/app/node_modules/ts-node/dist/index.js:851:20)
[cy:run  ]     at Module.load (node:internal/modules/cjs/loader:1125:32)
[cy:run  ]     at Function.Module._load (node:internal/modules/cjs/loader:965:12)
[cy:run  ]     at Module.require (node:internal/modules/cjs/loader:1149:19)
[cy:run  ]     at require (node:internal/modules/helpers:121:18)
```

### Desired behavior

Cypress e2e can start executing without bailing. Cypress e2e tests could run on v16.0 of @badeball/cypress-cucumber-preprocessor

### Test code to reproduce
N.A.

### Versions

* **Cypress version**: 12.13.0
* **Preprocessor version**: 17.1.1
* **Node version**: 20.2.0
* **OS**: macOS Darwin 13.4 on Apple M2 Max

### Checklist

- [ V ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ V ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ V ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by yeongsheng-tan** [comment]
Finally found the issue and it's not related to `cypress-cucumber-preprocessor` but rather an optimisation in `.yarnclean` that removed the `doc` dir for `js-yaml` node_module which is a transitive dependency of `cypress-cucumber-preprocessor` that prevented cypress with `cypress-cucumber-preprocessor` after version `17.x` to boot up correctly.

[Link to the issue described here](https://github.com/okonet/lint-staged/issues/1166).
