### ISSUE TITLE
"TypeError: anymatch is not a function" after update from v2 -> v3+

### ISSUE THREAD

**Issue by brvdpu** [badeball/cypress-cucumber-preprocessor#504]
I am updating my example setup to use that latest versions of cypress, tsify, typescript and your (nice) cypress-cucumber-preprocessor. Everything works fine until I update the cucumber-preprocessor from v2.5.5 to v3.0.0. Then I get the following error when trying to run a test (which did not occur in 2.5.5):
```
TypeError: anymatch is not a function
```

### Current behavior

![Screenshot 2021-02-09 at 10 55 04](https://user-images.githubusercontent.com/5774726/107347048-b0aa8980-6ac5-11eb-9a94-aead22e76128.png)

### Desired behavior

No anymatch error, like when using 2.5.5

### Test code to reproduce
Clone this repo:
https://gitlab.com/boterbram/cypress-setup

Then:
```
npm install
npm run cypress:open

# Start the example feature, everything OK, then close

npm install cypress-cucumber-preprocessor@3
npm run cypress:open

# Start example feature, now the opened browser window will close and the error shown.
```

### Versions

* **Cypress version**: 6.4.0
* **Preprocessor version**: 3.0.0 or higher
* **Node version**: 14.15.4
* **OSX version**: 10.15.7

**Comment by lgandecki** [comment]
Thanks for the reproduction.
Interestingly enough using yarn seems to work.
This is caused by a mismatch of anymatch versions between what cypress browserify uses and our chokidar uses. one of those anymatches exposes itself as .default and another not :) 

it should be fixed today by #505

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
