### ISSUE TITLE
Extending Common Step Definitions to a node_module

### ISSUE THREAD

**Issue by tomatobrown** [badeball/cypress-cucumber-preprocessor#272]
(it's very possible this functionality existing and I just missed it)

I'd like to be able to create a shared lib that lives as a node_module that I can publish and then share across different projects.  It seems like this should work to define the common path like: 
 `"commonPath": "node_modules/@privateNodeMode/step_definitions/",`
 when I do that it resolves in a `Error: Cannot find module` error message

I also tried setting the location of step definitions to: `"step_definitions": "node_modules/@privateNodeMode/step_definitions/",` and this actually works, however after I do this and create a step definition in the same folder as my feature file (non-common) then my test does not have access to the non-common step definition.

Ultimately, is there a recommended approach to extending step definitions that are stored inside of a node_module?

**Comment by lgandecki** [comment]
Can you just add a js file in the top-level common folder that will require the package with step definitions? I imagine there would be a package with an index.js file that requires other, individual files with steps.

**Comment by iambacon** [comment]
@lgandecki I have followed your suggestion and added a js file to the common folder to require the node module with my common steps.

This works fine when I run a single feature file, however when I run all, after the first feature file has run the rest fail as they can't find the common steps in my node module.

Do you know how this can run for all test feature files?

**Comment by alexkrolick** [comment]
I've also found that importing a module from the common directory that calls `Given`, `When`, `Then` doesn't seem to make the module's step definitions available.

**Comment by aureyia** [comment]
I'm encountering a similar issue when updating from 2.5.0 to 4.1.2. We use an index.js file in the `cypress/support/step_definitions` directory. When we try to import a package using: `import '@shared-package';` We get the following error from cypress during a execution: Where we see the error: `Step implementation missing for: 'step'` Though when we import files from a different directory such as `../../shared/steps` it works fine.
```js
// index.js

// Cannot find any steps within this package.
import '@shared-package';

// Steps imported from here work fine.
import '../../shared/steps/test.steps';
```
We use the `"nonGlobalStepDefinitions": false` in our package.json
```json
// package.json
{
  ...
   "cypress-cucumber-preprocessor": {
      "nonGlobalStepDefinitions": false
    }
}
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
